leave complicated packages to the end

diff --git a/bin/build b/bin/build
--- a/bin/build
+++ b/bin/build
@@ -15,28 +15,22 @@ if [[ ! -x local/bin/port ]]; then
     perl -pe 's{\$\$\$PANCAKE_ROOT\$\$\$}{$ENV{"PWD"}}eg' $a > ${a%.template} 
   done
 
-  exit
-
   pushd MacPorts-2.0.3 > /dev/null
-
-  ./configure --prefix="$_pth_local" --with-install-user=$(id -u -n) --with-install-group=$(id -g -n)
-  make -j 2
-  make install
-  hash -r
-
+    ./configure --prefix="$_pth_local" --with-install-user=$(id -u -n) --with-install-group=$(id -g -n)
+    make -j 2
+    make install
+    hash -r
   popd > /dev/null
 fi
 
 port install figlet bash wget curl rsync 
 port install tcl +threads
 port install git-core +svn +bash_completion
-port install git-flow
-port install rpm yum
-port install gnupg gpg-agent runit openvpn daemontools dtach screen
-port install squid
-port install dhcp dhcping tftp-hpa bind9
-port install nmap htop fping 
-port install ipmitool || true # fails
+port install gnupg gpg-agent 
+port install runit daemontools
+port install dtach screen tmux
+port install openvpn dhcp tftp-hpa bind9 squid
+port install nmap htop fping dhcping
 port install openssh +mute_fake_xauth
 port install fuse4x
 
@@ -49,19 +43,7 @@ port install xorg-server xmodmap xsetroot xterm
 port install xv xpdf
 port install tightvnc +no_server
 
-# port install firefox-x11 +official_branding || true # fails
-
 port install mplayer-devel +x11
-
-port install haskell-platform
-if [[ -n $CLEAN ]]; then
-  rm -rf ~/.cabal ~/.ghc
-
-  cabal update
-  cabal install xmonad-0.9.1
-  cabal install xmonad-contrib-0.9.1 --flags="-use_xft"
-  cabal install xmobar
-fi
 
 port install irssi watch unrar
 port install mercurial 
@@ -84,7 +66,6 @@ if [[ -n $CLEAN ]]; then
   gem install bundler -v 1.0.21
 fi
 
-
 port install libev
 port install emacs +gtk
 port install vim +x11 +ruby
@@ -92,11 +73,22 @@ port install macvim +ruby
 port install iterm2 
 
 port install cdrtools mtools
-port install qt4-mac -quartz
-
-# port install virtualbox || true # fails
 
 port install mysql5
 
 port install links +x11
 
+port install haskell-platform
+if [[ -n $CLEAN ]]; then
+  rm -rf ~/.cabal ~/.ghc
+
+  cabal update
+  cabal install xmonad-0.9.1
+  cabal install xmonad-contrib-0.9.1 --flags="-use_xft"
+  cabal install xmobar
+fi
+
+# port install firefox-x11 +official_branding || true # fails
+
+# port install qt4-mac -quartz
+# port install virtualbox || true # fails
