latest jason

diff --git a/libexec/_sub b/libexec/_sub
--- a/libexec/_sub
+++ b/libexec/_sub
@@ -1,17 +1,26 @@
 #!/bin/bash
 
-: ${_JASON_RUBY:=}
-: ${_JASON_WHICH_RUBY:=deploy_ruby}
+if [[ "${BASH_SOURCE##*/}" != "_sub" ]]; then
+  shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
+  source "$shome/libexec/_jason"
+  set -- "$BASH_SOURCE" "$@"
+fi
+
+if [[ "$(type -t main)" != "function" ]]; then
+function main {
+  if [[ "$#" > 0 ]]; then
+    logger_fatal "Command $sub_base $1 not implemented"
+  else
+    logger_fatal "Command $sub_base not implemented"
+  fi
+  exit 1
+}
+fi
 
 function sub {
   local bsource="$1"; shift
   local sub_base="$(basename "$bsource")"
   local bsource_cmd="$shome/libexec/${sub_base}"
-
-  local ruby_loader=
-  if [[ -n "$_JASON_RUBY" ]]; then
-    ruby_loader="rvm-exec $_JASON_RUBY "
-  fi
 
   if [[ "$bsource_cmd" = "$bsource" ]]; then
     FLAGS_SUB="$FLAGS_TRUE"
@@ -28,25 +37,22 @@ function sub {
 
       if [[ -x "$sub_cmd" ]]; then
         shift
-        exec ${ruby_loader}"$sub_cmd" "$@"
+        exec "$sub_cmd" "$@"
       fi
     fi
   fi
 
   if [[ -x "$bsource_cmd" && "$bsource_cmd" != "$bsource" ]]; then
-    exec ${ruby_loader}"$bsource_cmd" "$@"
+    exec "$bsource_cmd" "$@"
   else
-    main "$@"
+    if [[ "$(type -t main)" = "function" ]]; then
+      main "$@"
+    else
+      logger_fatal "Can't run $sub_base, missing main function"
+      exit 1
+    fi
   fi
 }
-
-if [[ "$shome/config/deploy.yml" ]]; then
-  export _JASON_RUBY="$(ryaml "$shome/config/deploy.yml" "$_JASON_WHICH_RUBY")"
-fi
-
-if [[ ! -x "$(which rvm-exec 2>&1 || true)" ]]; then
-  PATH="$PATH:$HOME/.rvm/bin:/usr/local/rvm/bin"
-fi
 
 if [[ "$#" > 0 ]]; then
   sub "$@"  
